ModeloFilmersGen/WebApplication2/Controllers/PeliculaController.cs
using Microsoft.AspNetCore.Mvc;
using ModeloFilmersGen.Infraestructure.Repository.Pruebadeesquemaproyecto;
using ModeloFilmersGen.ApplicationCore.CEN.Pruebadeesquemaproyecto;
using ModeloFilmersGen.ApplicationCore.EN.Pruebadeesquemaproyecto;
using WebApplication2.Models;
using WebApplication2.Assemblers;


namespace WebApplication2.Controllers
{
    public class PeliculaController : BasicController
    {

        public ActionResult anyadirPeliculaAWatchList(string idPelicula, string idUsuario)
        {
            SessionInitialize();
            int idP = int.Parse(idPelicula);
            UsuarioRepository usuarioRepository = new UsuarioRepository();
            UsuarioCEN usuarioCEN = new UsuarioCEN(usuarioRepository);
            usuarioCEN.AsignarPeliculaWatchList(idUsuario, new List<int> { idP });
            SessionClose();
            TempData["Success"] = "Has añadido una pelicula a ver más tarde exitosamente";
            return Json(new { success = true });

            
        }

        public ActionResult buscaRapidoPeliculas(string searchString)
        {
            SessionInitialize();
            PeliculaRepository peliRepository = new PeliculaRepository();
            PeliculaCEN peliCEN = new PeliculaCEN(peliRepository);

            IList<PeliculaEN> peliPorNombre = new List<PeliculaEN>();

            peliPorNombre = peliCEN.DamePeliculaPorNombre(searchString);

            var listaPelis = new List<object>();

            foreach(var i in peliPorNombre)
            {
                var nombres = new
                {
                    nombre = i.Nombre,
                    id = i.Id
                };

                listaPelis.Add(nombres);
            }

            return Json(listaPelis);
        }


        public ActionResult buscaRapidoGenero(string searchString)
        {
            SessionInitialize();
            PeliculaRepository peliRepository = new PeliculaRepository(session);
            PeliculaCEN peliCEN = new PeliculaCEN(peliRepository);

            IList<PeliculaEN> todas = new List<PeliculaEN>();

            todas = peliCEN.DameTodos(0, -1);

            var listaGenero = new List<String>();

            foreach (var i in todas) {
                foreach (var f in i.Genero) {
                    if (!listaGenero.Contains(f)) {
                        listaGenero.Add(f);
                    }
                }
            }

            var listaGeneroFiltrada = new List<Object>();
            foreach (var i in listaGenero)
            {
                if (i.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    var generos = new
                    {
                        genero = i
                    };
                    listaGeneroFiltrada.Add(generos);
                }
            }

            return Json(listaGeneroFiltrada);
        }




        // GET: PeliculaController
        public ActionResult Index(string searchString, string searchanyo, string searchValoracion, string searchGen)
        {
            SessionInitialize();
            PeliculaRepository peliRepository = new PeliculaRepository();
            PeliculaCEN peliCEN = new PeliculaCEN(peliRepository);

            IList<PeliculaEN> peliPorNombre = new List<PeliculaEN>();
            IList<PeliculaEN> peliPorFiltro = new List<PeliculaEN>();

            // Filtrar por nombre si se proporciona una cadena de búsqueda
            if (!string.IsNullOrEmpty(searchString))
            {
                peliPorNombre = peliCEN.DamePeliculaPorNombre(searchString);
            }
            else 
            {
                peliPorNombre = peliCEN.DameTodos(0,-1);
            }

            // Aplicar filtros si se proporcionan
            int? anyo = null;
            if (!string.IsNullOrEmpty(searchanyo) && int.TryParse(searchanyo, out int year))
            {
                anyo = year;
            }

            int? puntuacion = null;
            if (!string.IsNullOrEmpty(searchValoracion) && int.TryParse(searchValoracion, out int rating))
            {
                puntuacion = rating;
            }

            if (!string.IsNullOrEmpty(searchGen) || anyo != null || puntuacion != null)
            {
                peliPorFiltro = peliCEN.DamePeliculasPorFiltro(searchGen, anyo, puntuacion);
            }
            else
            {
               peliPorFiltro = peliCEN.DameTodos(0, -1);
            }

            IList<PeliculaEN> resultado = new List<PeliculaEN>();

            resultado = peliPorNombre.Intersect(peliPorFiltro).ToList();
           

            IEnumerable<PeliculaViewModel> listPelis = new PeliculaAssembler().ConvertirListEnToViewModel(resultado).ToList();
            SessionClose();

            return View(listPelis);
        }

        // GET: PeliculaController/Details/5
        public ActionResult Details(int id)
        {
            SessionInitialize();
            PeliculaRepository pelRep = new PeliculaRepository(session);
            PeliculaCEN pelCEN = new PeliculaCEN(pelRep);

            PeliculaEN pelEN = pelCEN.DamePorOID(id);

            PeliculaViewModel pelVM = new PeliculaAssembler().ConvertirEnToViewModel(pelEN);
            List<string> generos = new PeliculaAssembler().ObtenerGeneros(pelEN);
            IList<string> comentatios = new PeliculaAssembler().ObtenerComentarios(pelEN);

            SessionClose();

            return View(pelVM);
           
        }

        // GET: PeliculaController/Create
        public ActionResult Create()
        {

            return View();

        }

        // POST: PeliculaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PeliculaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PeliculaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PeliculaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PeliculaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ModeloFilmersGen/WebApplication2/Controllers/PlaylistController.cs
using Microsoft.AspNetCore.Mvc;
using NHibernate;
using ModeloFilmersGen.Infraestructure.CP;
using ModeloFilmersGen.Infraestructure.Repository.Pruebadeesquemaproyecto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using ModeloFilmersGen.ApplicationCore.CEN.Pruebadeesquemaproyecto;
using ModeloFilmersGen.ApplicationCore.EN.Pruebadeesquemaproyecto;
using WebApplication2.Models;
using WebApplication2.Assemblers;
using ModeloFilmersGen.ApplicationCore.CP.Pruebadeesquemaproyecto;

namespace WebApplication2.Controllers
{
    public class PlaylistController : BasicController
    {


        public ActionResult desAsignar(string idPelicula, string idPlaylist)
        {

            SessionInitialize();

            PlaylistRepository playlistRepository = new PlaylistRepository();
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
            playlistCEN.DesasignarPeliculas(int.Parse(idPlaylist), new List<int> { int.Parse(idPelicula) });

            SessionClose();

            return Json(new { success = true }); ;
        }






        [HttpPost]
        public IActionResult AgregarPeliculaAPlaylist(string idPelicula, string idPlaylist)
        {
            SessionInitialize();
            int idP = int.Parse(idPelicula);
            int idPlay = int.Parse(idPlaylist);

            PlaylistRepository playlistRepository = new PlaylistRepository();
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);      

            playlistCEN.AsignarPeliculas(idPlay, new List<int> { idP });

            SessionClose();
            return Json(new { success = true, redirectUrl = Url.Action("Details", new { id = idPlay }) }); ;

        }

        [HttpPost]
        public IActionResult AgregarPlaylistAFavoritos(string idPlaylist, string idUsuario)
        {
            SessionInitialize();

            int idPlay = int.Parse(idPlaylist);

            PlaylistRepository playlistRepository = new PlaylistRepository();
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
            UsuarioRepository usR = new UsuarioRepository(session);
            UsuarioCEN usuarioCEN = new UsuarioCEN(usR);

            playlistCEN.AsignarSuscriptor(idPlay, new List<string> { idUsuario });

            TempData["Success"] = "¡La playlist ha sido añadida a favoritos!";


            SessionClose();

            return Json(new { success = true });
        }

        private IDictionary<int, IList<string>> ObtenerCaratulasParaPlaylists(IList<PlaylistEN> playlists)
        {
            IDictionary<int, IList<string>> caratulasPorPlaylist = new Dictionary<int, IList<string>>();

            foreach (var playlist in playlists)
            {
                IList<string> caratulasDePlaylist = new List<string>();
                foreach (var movie in playlist.Peliculas)
                {
                    caratulasDePlaylist.Add(movie.Caratula);
                }
                caratulasPorPlaylist.Add(playlist.Id, caratulasDePlaylist); // Asume que 'Id' es un identificador único de PlaylistEN
            }

            return caratulasPorPlaylist;
        }

        public ActionResult PlayListByUsuario()
        {
            SessionInitialize();
            UsuarioViewModel usuario = HttpContext.Session.Get<UsuarioViewModel>("usuario");
            UsuarioRepository usR = new UsuarioRepository(session);
            UsuarioCEN usuarioCEN = new UsuarioCEN(usR);
            var playlistENs = new List<object>();
            if (usuario != null)
            {
                UsuarioEN usuarioEN = usuarioCEN.DamePorOID(usuario.Email);
                foreach (var i in usuarioEN.Playlistcreadas)
                {
                    var playlistItem = new
                    {
                        id = i.Id,
                        nombrePlaylist = i.Nombre,
                        descripcion = i.Descripcion
                    };

                    playlistENs.Add(playlistItem);
                }
            }
            return Json(playlistENs);
        }

        public ActionResult IndexCarrusel()
        {
            // Inicializa la sesión
            SessionInitialize();

            // Creación y configuración del repositorio y del CEN de Playlist
            PlaylistRepository playlistRepository = new PlaylistRepository(session);
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);

            // Obtención de todas las playlists
            IList<PlaylistEN> playEN = playlistCEN.DameTodos(0, -1);

            // Conversión de las entidades PlaylistEN a ViewModels
            IList<PlaylistViewModel> listPlay = new PlaylistAssembler().ConvertirListEnToViewModel(playEN).ToList();

            // Obtención de las carátulas para cada playlist
            IDictionary<int, IList<string>> caratulas = ObtenerCaratulasParaPlaylists(playEN);

            // Creación del ViewModel para la vista
            var viewModel = new PlatyListyPeliculasFotosViewModel
            {
                Playlist = listPlay,
                CaratulasPorPlaylist = caratulas // Asegúrate de tener esta propiedad en tu ViewModel
            };

            // Cierre de la sesión
            SessionClose();

            // Retorna la vista con el ViewModel
            return View(viewModel);
        }




        // GET: PlaylistController
        public ActionResult Index()
        {
            // Inicializa la sesión
            SessionInitialize();

            // Creación y configuración del repositorio y del CEN de Playlist
            PlaylistRepository playlistRepository = new PlaylistRepository(session);
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);

            // Obtención de todas las playlists
            IList<PlaylistEN> playEN = playlistCEN.DameTodos(0, -1);

            // Conversión de las entidades PlaylistEN a ViewModels
            IList<PlaylistViewModel> listPlay = new PlaylistAssembler().ConvertirListEnToViewModel(playEN).ToList();

            // Obtención de las carátulas para cada playlist
            IDictionary<int, IList<string>> caratulas = ObtenerCaratulasParaPlaylists(playEN);

            // Creación del ViewModel para la vista
            var viewModel = new PlatyListyPeliculasFotosViewModel
            {
                Playlist = listPlay,
                CaratulasPorPlaylist = caratulas // Asegúrate de tener esta propiedad en tu ViewModel
            };

            // Cierre de la sesión
            SessionClose();

            // Retorna la vista con el ViewModel
            return View(viewModel);

        }

        // GET: PlaylistController/Details/5
        public ActionResult Details(int id)
        {
            SessionInitialize();
            PlaylistRepository playlistRepository = new PlaylistRepository(session);
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);

            PlaylistEN playlistEN = playlistCEN.DamePorOID(id);
            PlaylistViewModel playlistViewModel = new PlaylistAssembler().ConvertirEnToViewModel(playlistEN);

            IList<PeliculaEN> peliculasEnPlay = new List<PeliculaEN>();

            foreach(var i in playlistEN.Peliculas)
            {
                peliculasEnPlay.Add(i);
            }

            IList<PeliculaViewModel> p = new PeliculaAssembler().ConvertirListEnToViewModel(peliculasEnPlay).ToList();

            var vista = new PlayList_PeliculasViewModel
            {
                Playlist = playlistViewModel,
                Pelicula = p
            };

            SessionClose();

            return View(vista);
        }

        // GET: PlaylistController/Create
        public ActionResult Create()
        {
            SessionInitialize();
            PlaylistRepository playlistRepository = new PlaylistRepository(session);
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
            PlaylistEN playlistEN = new PlaylistEN();
            PlaylistViewModel playlistViewModel = new PlaylistAssembler().ConvertirEnToViewModel(playlistEN);

            SessionClose();

            return View(playlistViewModel);
        }

        // POST: PlaylistController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlaylistViewModel play)
        {
            try
            {
                UsuarioViewModel usuario = HttpContext.Session.Get<UsuarioViewModel>("usuario");
                PlaylistRepository playlistRepository = new PlaylistRepository();
                PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
                int id =  playlistCEN.CrearPlaylist(play.nombre, play.Descripcion, usuario.Email);
                return RedirectToAction("Details", new { id });
            }
            catch
            {
                return View();
            }
        }

        // GET: PlaylistController/Edit/5
        public ActionResult Edit(int id)
        {
            SessionInitialize();
            PlaylistRepository playlistRepository = new PlaylistRepository();
            PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);

            PlaylistEN playlistEN = playlistCEN.DamePorOID(id);
            PlaylistViewModel playlistViewModel = new PlaylistAssembler().ConvertirEnToViewModel(playlistEN);

            SessionClose();
            return View(playlistViewModel);
        }

        // POST: PlaylistController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PlaylistViewModel play)
        {
            try
            {
                PlaylistRepository playlistRepository = new PlaylistRepository();
                PlaylistCEN playlistCEN = new PlaylistCEN(playlistRepository);
                playlistCEN.ModificarPlaylist(id, play.nombre, play.Descripcion);

ModeloFilmersGen/WebApplication2/Views/Usuario/Details.cshtml
@model WebApplication2.Models.UsuarioViewModel

@{
    ViewData["Title"] = "Details";
    UsuarioViewModel usuario = Context.Session.Get<UsuarioViewModel>("usuario");

    @if (usuario != null && usuario.Email == @Model.Email)
    {
        <script>
            window.location.href = '/Usuario/DetailsPerfil/@Model.Email';
        </script>
    }

}

<div class="row align-items-center">
    <div class="col-sm-4 pb-3" style="max-width: 250px; max-height: 250px;">
        <img src="/Img/@(Model.Avatar).jpeg" alt="Avatar" class="img-fluid rounded-circle" />
    </div>
    <div class="col-sm-8 pb-3">

        <div class="row align-items-center">
            <div class="col-2">
                <h3>@Model.NombreUsuario</h3>
            </div>
            @if (usuario != null && usuario.Email != @Model.Email)
            {
                <div class="col-auto">
                    
                        @if (usuario.UsuariosSeguidos != null)
                        {
                            // Comprobamos si ya está siguiendo al usuario
                            bool isFollowing = usuario.UsuariosSeguidos.Contains(Model.Email);
                            @if (isFollowing)
                            {
                                <button type="button" data-follow-id="@Model.Email" class="btn btn-success btn-sm" onclick="followUnfollow('@usuario.Email', '@Model.Email', true)">Siguiendo</button>
                            }
                            else
                            {
                                <button type="button" data-follow-id="@Model.Email" class="btn btn-outline-primary btn-sm" onclick="followUnfollow('@usuario.Email', '@Model.Email', false)">Seguir</button>
                            }
                        }

                    
                </div>
            }
        </div>


        <h4>@Model.Nombre</h4>
        <br />
        <div class="row">
            <div class="col-sm-4 text-center">
                <h5>@Model.Seguidores</h5>
                <p id="Seguidores">Seguidores</p>
            </div>
            <div class="col-sm-4 text-center">
                <h5>@Model.Seguidos</h5>
                <p id="Seguidos">Seguidos</p>
            </div>
            <div class="col-sm-4 text-center">
                <h5>@Model.PelisVistas</h5>
                <p>Películas</p>
            </div>
        </div>
    </div>
    <hr />
    <div id="vistasUsuario">
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

@section Scripts {
    <script>
        $(document).ready(function () {
            var idUsuario = '@Model.Email'; // Reemplaza esto con tu lógica para obtener el ID del usuario
            $.get('/Usuario/Vistas/' + idUsuario, function (data) {
                $('#vistasUsuario').html(data);
            });
        });
    </script>



    <script>
        function followUnfollow(userId, followedId, isFollowing) {
            var btn = $("[data-follow-id='" + followedId + "']");
            btn.prop('disabled', true);

            var url = isFollowing ? '@Url.Action("Unfollow", "Notificaciones")' : '@Url.Action("Follow", "Notificaciones")';
            $.ajax({
                url: url,
                type: 'POST',
                data: { id: userId, idSeguido: followedId },
                success: function () {
                    // Actualizar la interfaz de usuario aquí
                    btn.prop('disabled', false);
                    if (isFollowing) {
                        btn.text("Seguir").removeClass("btn-success").addClass("btn-outline-primary").attr("onclick", "followUnfollow('" + userId + "', '" + followedId + "', false)");
                    } else {
                        btn.text("Siguiendo").removeClass("btn-outline-primary").addClass("btn-success").attr("onclick", "followUnfollow('" + userId + "', '" + followedId + "', true)");
                    }

                    actualizarSesion(userId);
                    location.reload();
                },
                error: function () {
                    alert("Error al procesar la solicitud.");
                    btn.prop('disabled', false);
                }
            });
        }

        function actualizarSesion(userId) {
                $.ajax({
                    url: '@Url.Action("RecargarSesion", "Notificaciones")',
                    type: 'SET',
                    data: {idUsuario: userId},
                    success: function () {
                    },
                    error: function () {
                        alert("Error al procesar la solicitud.");
                        btn.prop('disabled', false);
                    }
                });

            }
    </script>
}

ModeloFilmersGen/WebApplication2/Views/Usuario/Index.cshtml
@model IEnumerable<WebApplication2.Models.UsuarioViewModel>

@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Buscar</h1>
        </div>
    </div>

    <div class="row mt-3 mb-3">
        <!-- Search form -->
        <form action="@Url.Action("Index", "Usuario")" method="GET" class="form-inline w-50 mb-3" id="searchForm">
            <div class="input-group rounded">
                <input type="search" name="searchString" class="form-control rounded" placeholder="Buscar por nombre" aria-label="Search" aria-describedby="search-addon" id="searchInput" />
                <button class="input-group-text border-0 ms-2" id="search-addon">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </form>

        <hr />

        <div class="col-md-12 d-flex justify-content-center">
            <!-- Botón para ir a la sección de películas -->
            <a href="@Url.Action("Index", "Pelicula")" class="btn mx-2">Películas</a>
            <a href="@Url.Action("Index", "Usuario")" class="btn mx-2 disabled border-primary">Usuarios</a>
        </div>
    </div>


    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-2 col-md-4 col-sm-6 col-12">
                <div>
                    <a href="@Url.Action("Details", "Usuario", new { id = item.Email })">
                        <img src="/Img/@(item.Avatar).jpeg" class="card-img-top rounded-circle img-fluid" alt="Avatar" style="width: 170px; height: 170px;">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title text-center">@item.NombreUsuario</h5>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ModeloFilmersGen/WebApplication2/Views/Usuario/_CalendarioUsuario.cshtml
@model IEnumerable<WebApplication2.Models.PeliculaVistaViewModel>
@using System.Globalization
    <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    

    </head>

@{
    string mesAnterior = "";
    string yearAnterior = "";
}

<div class="row">
    <h5>Calendario</h5>
    @foreach (var item in Model)
    {
        var currentMonth = item.fecha.HasValue ? CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(item.fecha.Value.Month) : "Fecha no disponible";
        currentMonth = char.ToUpper(currentMonth[0]) + currentMonth.Substring(1);
        var currentYear = item.fecha.HasValue ? item.fecha.Value.Year.ToString() : "Fecha no disponible";
        if (currentMonth != mesAnterior || currentYear != yearAnterior)
        {
            <div class="col-12">
                <h4>@currentMonth @currentYear</h4>
            </div>
        }
        <div class="col-xxl-2 col-sm-6 col-12">
            <div class="card border-0">
                <div class="card-img-container">
                    <span class="day-badge">@item.fecha.Value.Day</span>
                    <a href="@Url.Action("Details", "Pelicula", new { id = item.idPelicula })">
                        <img src="@item.fotoPeli" class="card-img-top img-fluid" alt="Carátula">
                    </a>
                </div>

               
            </div>
            <div class="card-body row">
                <h5 class="card-title text-center col-12">@item.nombrePeli</h5>

                @{
                    int valoracionEntera = (int)item.valoracion;
                }
                <h5 class="col-6 d-flex align-items-center">
                    @{
                        for (int i = 0; i < valoracionEntera; i++)
                        {
                            <i class="bi bi-star-fill"></i>
                        }
                    }
                </h5>
                <div class="text-center col-3">
                    <a href="@Url.Action("Edit", "PeliculaVista", new { id = item.Id })" class="btn btn-outline-primary">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                </div>
                <div class="text-center col-3">
                    <a href="@Url.Action("Delete", "PeliculaVista", new { id = item.Id })" class="btn btn-outline-primary">
                        <i class="bi bi-trash3-fill"></i>
                    </a>
                </div>
            </div>
        </div>
        mesAnterior = currentMonth;
        yearAnterior = currentYear;
    }
</div>

ModeloFilmersGen/WebApplication2/Views/Usuario/_DeseosUsuario.cshtml
@model IEnumerable<WebApplication2.Models.PeliculaViewModel>

<div class="row">
    <h5>Para ver</h5>
    @foreach (var item in Model)
    {
        <div class="col-lg-2 col-md-4 col-sm-6 col-12">
            <div class="card border-0">
                <a href="@Url.Action("Details", "Pelicula", new { id = item.Id })">
                    <img src="@item.caratula" class="card-img-top img-fluid shadow p-1  bg-white rounded" alt="Carátula">
                </a>
                <div class="mask"></div>
                
            </div>

            <div class="card-body">
                <h5 class="card-title text-center">@item.nombre</h5>
            </div>
        </div>
    }
</div>

ModeloFilmersGen/WebApplication2/Views/Usuario/_PLayList.cshtml
@model IEnumerable<WebApplication2.Models.PlaylistViewModel>

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<div class="row">
    <h5>Playlists</h5>
    @foreach (var item in Model)
    {
        <a href="@Url.Action("Details", "Playlist", new { id = item.Id })" title="Details">
            <div class="hover-overlay">
                <div class="playlist-container">
                    <div class="row">
                        <div class="col-xl-8 text-black text-decoration-none">
                            <p>@Html.DisplayFor(modelItem => item.nombre)</p>
                            <p>@Html.DisplayFor(modelItem => item.Descripcion)</p>
                        </div>

                        <div class="col-xl-4">
                            <a href="@Url.Action("Edit", "Playlist", new { id = item.Id })" class="btn btn-success" title="Edit"><i class="fas fa-edit"></i></a>
                        </div>
                    </div>
                </div>
                <div class="mask"></div>
            </div>
        </a>
    }
</div>

ModeloFilmersGen/WebApplication2/Views/Usuario/_VistasUsuario.cshtml
<div class="row">
    <h5>Peliculas Vistas</h5>
    @foreach (var item in Model)
    {
        <div class="col-lg-2 col-md-4 col-sm-6 col-12">
            <div class="card border-0">
                <a href="@Url.Action("Details", "Pelicula", new { id = item.idPelicula })">
                    <img src="@item.fotoPeli" class="card-img-top img-fluid shadow p-1  bg-white rounded" alt="Carátula">
                </a>
                <div class="mask"></div>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center">@item.nombrePeli</h5>
            </div>
        </div>
    }
</div>