ModeloFilmersGen/WebApplication2/Models/NotificacionesViewModel.cs
using NHibernate.Linq.Functions;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class NotificacionesViewModel
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }


        public DateTime Fecha { get; set; }

      
        public String Contenido { get; set; }

      
        public Boolean Estado { get; set; }

       
        public Boolean Destacada { get; set; }

        [ScaffoldColumn(false)]
        public String IdUsuario { get; set; }

        public int idPelicula { get; set; }

        public string nombrePeli { get; set; }

        public String IdUsuarioEmisor {  get; set; }

        public ModeloFilmersGen.ApplicationCore.Enumerated.Pruebadeesquemaproyecto.AvatarEnum fotoUsuarioEmisor {  get; set; }

    }
}

ModeloFilmersGen/WebApplication2/Controllers/NotificacionesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModeloFilmersGen.ApplicationCore.CEN.Pruebadeesquemaproyecto;
using ModeloFilmersGen.ApplicationCore.CP.Pruebadeesquemaproyecto;
using ModeloFilmersGen.ApplicationCore.EN.Pruebadeesquemaproyecto;
using ModeloFilmersGen.Infraestructure.Repository.Pruebadeesquemaproyecto;
using WebApplication2.Assemblers;
using WebApplication2.Models;

using System.Linq;
using ModeloFilmersGen.Infraestructure.CP;

namespace WebApplication2.Controllers
{
    public class NotificacionesController : BasicController
    {
        // Lógica para seguir al usuario
        
        public IActionResult Follow(string id, string idSeguido)
        {

            SessionInitialize();
            UsuarioRepository usuarioRepository = new UsuarioRepository(session);

            UsuarioCP usuarioCP = new UsuarioCP(new SessionCPNHibernate());
            usuarioCP.Follow(id, idSeguido);
            SessionClose();



            return Ok();
        }

        public IActionResult RecargarSesion(string idUsuario)
        {
            SessionInitialize();
            UsuarioRepository usuarioRepo = new UsuarioRepository(session);
            UsuarioCEN usuCen = new UsuarioCEN(usuarioRepo);
           
            UsuarioEN usuEN = usuCen.DamePorOID(idUsuario);
            UsuarioViewModel usuVM = new UsuarioAssembler().ConvertirENToViewModel(usuEN);
            HttpContext.Session.Set<UsuarioViewModel>("usuario", usuVM);
            SessionClose();



            return Ok();
        }


        public IActionResult Unfollow(string id, string idSeguido)
        {

            SessionInitialize();
            UsuarioRepository usuarioRepository = new UsuarioRepository(session);

            UsuarioCP usuarioCP = new UsuarioCP(new SessionCPNHibernate());
            usuarioCP.Unfollow(id, idSeguido);
            SessionClose();

            return Ok();
        }

        // GET: NotificacionesController
        public ActionResult Index()
        {
            SessionInitialize();
            NotificacionesRepository notRepository = new NotificacionesRepository(session);
            UsuarioRepository usuarioRepository = new UsuarioRepository(session);
            PeliculaRepository peliculaRepository = new PeliculaRepository(session);

            NotificacionesCEN notCEN = new NotificacionesCEN(notRepository);
            PeliculaCEN pelCEN = new PeliculaCEN(peliculaRepository);
            UsuarioCEN usuCEN = new UsuarioCEN(usuarioRepository);

            UsuarioViewModel usuario = HttpContext.Session.Get<UsuarioViewModel>("usuario");

            UsuarioEN usEN = usuCEN.DamePorOID(usuario.Email);
            IList<NotificacionesEN> notsEN = usEN.Notificaciones.ToList();
            IList<NotificacionesViewModel> notificaionesVM = new List<NotificacionesViewModel>();

            foreach (var noti in notsEN)
            {
                UsuarioEN usEN2 = usuCEN.DamePorOID(noti.UsuariorEmisor);

                NotificacionesViewModel notiVM = new NotificacionesViewModel();

                if (noti.Pelicula != -1)
                {

                    PeliculaEN pelEN = pelCEN.DamePorOID(noti.Pelicula);

                    notiVM = new NotificacionesViewModel
                    {
                        Id = noti.Id,
                        Fecha = (DateTime)noti.Fecha,
                        Contenido = noti.Contenido,
                        Estado = noti.Estado,
                        Destacada = noti.Destacada,
                        IdUsuario = noti.Usuario.Email,
                        idPelicula = noti.Pelicula,
                        nombrePeli = pelEN.Nombre,
                        IdUsuarioEmisor = noti.UsuariorEmisor,
                        fotoUsuarioEmisor = usEN2.AvatarIcon,
                    };
                }
                else
                {

                    notiVM = new NotificacionesViewModel
                    {
                        Id = noti.Id,
                        Fecha = (DateTime)noti.Fecha,
                        Contenido = noti.Contenido,
                        Estado = noti.Estado,
                        Destacada = noti.Destacada,
                        IdUsuario = noti.Usuario.Email,
                        idPelicula = noti.Pelicula,
                        IdUsuarioEmisor = noti.UsuariorEmisor,
                        fotoUsuarioEmisor = usEN.AvatarIcon,
                    };

                }




                notificaionesVM.Add(notiVM);
            }


            SessionClose();

            return View(notificaionesVM);
        }

        // GET: NotificacionesController/Details/5
        public ActionResult Details(int id)
        {
            SessionInitialize();
            NotificacionesRepository notRepo = new NotificacionesRepository(session);
            NotificacionesCEN notCEN = new NotificacionesCEN(notRepo);

            NotificacionesEN notEN = notCEN.DamePorOID(id);

            NotificacionesViewModel notVM = new NotificacionesAssembler().ConvertirEnToViewModel(notEN);

            SessionClose();

            return View(notVM);
        }

        // GET: NotificacionesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NotificacionesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NotificacionesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NotificacionesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NotificacionesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NotificacionesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ModeloFilmersGen/WebApplication2/Controllers/PeliculaController.cs
using Microsoft.AspNetCore.Mvc;
using ModeloFilmersGen.Infraestructure.Repository.Pruebadeesquemaproyecto;
using ModeloFilmersGen.ApplicationCore.CEN.Pruebadeesquemaproyecto;
using ModeloFilmersGen.ApplicationCore.EN.Pruebadeesquemaproyecto;
using WebApplication2.Models;
using WebApplication2.Assemblers;


namespace WebApplication2.Controllers
{
    public class PeliculaController : BasicController
    {

        public ActionResult anyadirPeliculaAWatchList(string idPelicula, string idUsuario)
        {
            SessionInitialize();
            int idP = int.Parse(idPelicula);
            UsuarioRepository usuarioRepository = new UsuarioRepository();
            UsuarioCEN usuarioCEN = new UsuarioCEN(usuarioRepository);
            usuarioCEN.AsignarPeliculaWatchList(idUsuario, new List<int> { idP });
            SessionClose();
            TempData["Success"] = "Has añadido una pelicula a ver más tarde exitosamente";
            return Json(new { success = true });

            
        }

        public ActionResult buscaRapidoPeliculas(string searchString)
        {
            SessionInitialize();
            PeliculaRepository peliRepository = new PeliculaRepository();
            PeliculaCEN peliCEN = new PeliculaCEN(peliRepository);

            IList<PeliculaEN> peliPorNombre = new List<PeliculaEN>();

            peliPorNombre = peliCEN.DamePeliculaPorNombre(searchString);

            var listaPelis = new List<object>();

            foreach(var i in peliPorNombre)
            {
                var nombres = new
                {
                    nombre = i.Nombre,
                    id = i.Id
                };

                listaPelis.Add(nombres);
            }

            return Json(listaPelis);
        }


        public ActionResult buscaRapidoGenero(string searchString)
        {
            SessionInitialize();
            PeliculaRepository peliRepository = new PeliculaRepository(session);
            PeliculaCEN peliCEN = new PeliculaCEN(peliRepository);

            IList<PeliculaEN> todas = new List<PeliculaEN>();

            todas = peliCEN.DameTodos(0, -1);

            var listaGenero = new List<String>();

            foreach (var i in todas) {
                foreach (var f in i.Genero) {
                    if (!listaGenero.Contains(f)) {
                        listaGenero.Add(f);
                    }
                }
            }

            var listaGeneroFiltrada = new List<Object>();
            foreach (var i in listaGenero)
            {
                if (i.IndexOf(searchString, StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    var generos = new
                    {
                        genero = i
                    };
                    listaGeneroFiltrada.Add(generos);
                }
            }

            return Json(listaGeneroFiltrada);
        }




        // GET: PeliculaController
        public ActionResult Index(string searchString, string searchanyo, string searchValoracion, string searchGen)
        {
            SessionInitialize();
            PeliculaRepository peliRepository = new PeliculaRepository();
            PeliculaCEN peliCEN = new PeliculaCEN(peliRepository);

            IList<PeliculaEN> peliPorNombre = new List<PeliculaEN>();
            IList<PeliculaEN> peliPorFiltro = new List<PeliculaEN>();

            // Filtrar por nombre si se proporciona una cadena de búsqueda
            if (!string.IsNullOrEmpty(searchString))
            {
                peliPorNombre = peliCEN.DamePeliculaPorNombre(searchString);
            }
            else 
            {
                peliPorNombre = peliCEN.DameTodos(0,-1);
            }

            // Aplicar filtros si se proporcionan
            int? anyo = null;
            if (!string.IsNullOrEmpty(searchanyo) && int.TryParse(searchanyo, out int year))
            {
                anyo = year;
            }

            int? puntuacion = null;
            if (!string.IsNullOrEmpty(searchValoracion) && int.TryParse(searchValoracion, out int rating))
            {
                puntuacion = rating;
            }

            if (!string.IsNullOrEmpty(searchGen) || anyo != null || puntuacion != null)
            {
                peliPorFiltro = peliCEN.DamePeliculasPorFiltro(searchGen, anyo, puntuacion);
            }
            else
            {
               peliPorFiltro = peliCEN.DameTodos(0, -1);
            }

            IList<PeliculaEN> resultado = new List<PeliculaEN>();

            resultado = peliPorNombre.Intersect(peliPorFiltro).ToList();
           

            IEnumerable<PeliculaViewModel> listPelis = new PeliculaAssembler().ConvertirListEnToViewModel(resultado).ToList();
            SessionClose();

            return View(listPelis);
        }

        // GET: PeliculaController/Details/5
        public ActionResult Details(int id)
        {
            SessionInitialize();
            PeliculaRepository pelRep = new PeliculaRepository(session);
            PeliculaCEN pelCEN = new PeliculaCEN(pelRep);

            PeliculaEN pelEN = pelCEN.DamePorOID(id);

            PeliculaViewModel pelVM = new PeliculaAssembler().ConvertirEnToViewModel(pelEN);
            List<string> generos = new PeliculaAssembler().ObtenerGeneros(pelEN);
            IList<string> comentatios = new PeliculaAssembler().ObtenerComentarios(pelEN);

            SessionClose();

            return View(pelVM);
           
        }

        // GET: PeliculaController/Create
        public ActionResult Create()
        {

            return View();

        }

        // POST: PeliculaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PeliculaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PeliculaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PeliculaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PeliculaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ModeloFilmersGen/WebApplication2/Views/Notificaciones/Details.cshtml
@model WebApplication2.Models.NotificacionesViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>NotificacionesViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contenido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contenido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destacada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destacada)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ModeloFilmersGen/WebApplication2/Views/Notificaciones/Index.cshtml
@model IEnumerable<WebApplication2.Models.NotificacionesViewModel>

@{
    ViewData["Title"] = "Index";
}

@{
    UsuarioViewModel usuario = Context.Session.Get<UsuarioViewModel>("usuario");

    

}



<h1>Mis notificaciones</h1>

<div class="container mt-3">
    @foreach (var item in Model)
    {
        <div class="row mb-2">
            <!-- Icono de la notificación -->
            <div class="col-auto">
                <img src="/Img/@(item.fotoUsuarioEmisor).jpeg" class="card-img-top rounded-circle img-fluid" alt="Avatar" style="width: 80px; height: 80px;">
            </div>

            <!-- Fecha y hora de la notificación -->
            <div class="col-auto text-secondary">
                @Html.DisplayFor(modelItem => item.Fecha)
            </div>

            <!-- Contenido de la notificación -->
            <div class="col">
                @Html.DisplayFor(modelItem => item.Contenido)
            </div>

            @if (item.idPelicula != -1)
            {
                <div class="col-auto">
                    <a href="@Url.Action("Details", "Pelicula", new { id = item.idPelicula })"> @item.nombrePeli </a>
                </div>
            }
            else
            {
                // Comprobamos si ya está siguiendo al usuario
                bool isFollowing = usuario.UsuariosSeguidos.Contains(item.IdUsuarioEmisor);
                <div class="col-auto">
                    @if (isFollowing)
                    {
                        <button type="button" data-follow-id="@item.IdUsuarioEmisor" class="btn btn-success btn-sm" onclick="followUnfollow('@usuario.Email', '@item.IdUsuarioEmisor', true)">Siguiendo</button>
                    }
                    else
                    {
                        <button type="button" data-follow-id="@item.IdUsuarioEmisor" class="btn btn-outline-primary btn-sm" onclick="followUnfollow('@usuario.Email', '@item.IdUsuarioEmisor', false)">Seguir</button>
                    }
                </div>
            }
        </div>
    }


    @section Scripts {
        <script>
            function followUnfollow(userId, followedId, isFollowing) {
                var btn = $("[data-follow-id='" + followedId + "']");
                btn.prop('disabled', true);

                var url = isFollowing ? '@Url.Action("Unfollow", "Notificaciones")' : '@Url.Action("Follow", "Notificaciones")';
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: { id: userId, idSeguido: followedId },
                    success: function () {
                        // Actualizar la interfaz de usuario aquí
                        btn.prop('disabled', false);
                        if (isFollowing) {
                            btn.text("Seguir").removeClass("btn-success").addClass("btn-outline-primary").attr("onclick", "followUnfollow('" + userId + "', '" + followedId + "', false)");
                        } else {
                            btn.text("Siguiendo").removeClass("btn-outline-primary").addClass("btn-success").attr("onclick", "followUnfollow('" + userId + "', '" + followedId + "', true)");
                        }
                        actualizarSesion(userId);
                    },
                    error: function () {
                        alert("Error al procesar la solicitud.");
                        btn.prop('disabled', false);
                    }
                });
            }



            function actualizarSesion(userId) {
                $.ajax({
                    url: '@Url.Action("RecargarSesion", "Notificaciones")',
                    type: 'SET',
                    data: {idUsuario: userId},
                    success: function () {
                    },
                    error: function () {
                        alert("Error al procesar la solicitud.");
                        btn.prop('disabled', false);
                    }
                });

            }

        </script>
    }